import * as Joi from 'joi';

export default Joi.object({
  NODE_ENV: Joi.string(),
  DATABASE_PORT: Joi.number().port().required(),
  DATABASE_USER: Joi.string().required(),
  DATABASE_HOST: Joi.string().required(),
  DATABASE_PASS: Joi.string().required(),
  DATABASE_NAME: Joi.string().required(),
  DATABASE_SYNC: Joi.boolean().required(),
  DATABASE_AUTOLOAD: Joi.boolean().required(),
  JWT_ACCESS_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_TTL: Joi.string().required(),
  JWT_REFRESH_TTL: Joi.string().required(),
  JWT_REFRESH_TTL_MS: Joi.number().required(),
  JWT_HASH_SALT: Joi.string().required(),
  CORS_ORIGIN: Joi.string().required(),
  API_VERSION: Joi.string().required(),
  SERVER_DOMAIN: Joi.string().required(),
  CLIENT_DOMAIN: Joi.string().required(),
  COOKIE_MAXAGE_ACCESS: Joi.number().required(),
  COOKIE_MAXAGE_REFRESH: Joi.number().required(),
  COOKIE_SECURE: Joi.string().required(),
  COOKIE_HTTPONLY: Joi.string().required(),
  COOKIE_SAMESITE: Joi.string().required(),
  UPLOAD_PATH_AVATARS: Joi.string().required(),
  UPLOAD_PATH_POSTS: Joi.string().required(),
  UPLOAD_PATH_REELS: Joi.string().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_SECURE: Joi.string().required(),
  MAIL_USERNAME: Joi.string().required(),
  MAIL_PASSWORD: Joi.string().required()
});